/* eslint-env node */
const fs = require('fs');
const path = require('path');

try {
  const target = path.join(
    __dirname,
    '..',
    'node_modules',
    'react-native',
    'jest',
    'setup.js',
  );
  const content = `/** Redirect react-native jest setup to the repository wrapper (auto-generated by postinstall)
 */
try {
  module.exports = require('../../../__mocks__/rn-jest-setup-wrapper.js');
} catch (e) {
  module.exports = {};
}
`;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, 'utf8');
  console.log('[postinstall] Wrote', target);
} catch (err) {
  console.error(
    '[postinstall] failed to write react-native/jest setup redirect:',
    err && err.message,
  );
  process.exitCode = 0;
}
