name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [[self-hosted, macOS, X64], [self-hosted, windows]]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Check runner
        run: |
          echo "Hello from the self-hosted runner"
          pwd
          whoami
          uname -a
